# Exported from Render on 2025-10-16T21:36:09Z
version: "1"
services:
- type: web
  name: Aligner-360-Backend
  runtime: node
  repo: https://github.com/Misba9/Aligner-360-Backend
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: ADMIN_PANEL_URL
    sync: false
  - key: FRONTEND_URL
    sync: false
  region: oregon
  buildCommand: npm install; npm run build
  startCommand: npm run start
  autoDeployTrigger: commit
